export default initialActions = [
  {
    actionId: 1,
    actionTitle: "actionTitle",
    actionDescription: "actionDescription",
    actionType: "actionType",
    causeTitle: "causeTitle",
    campaignTitle: "campaignTitle",
    campaignDescription: "campaignDescription",
    organizationContact: "organizationContact",
    organizationTitle: "organizationTitle",
    organizationDescription: "organizationDescription",
    reward: 100},
    {
      actionId: 2,
      actionTitle: "actionTitle",
      actionDescription: "actionDescription",
      actionType: "actionType",
      causeTitle: "causeTitle",
      campaignTitle: "campaignTitle",
      campaignDescription: "campaignDescription",
      organizationContact: "organizationContact",
      organizationTitle: "organizationTitle",
      organizationDescription: "organizationDescription",
      reward: 100},
      {
        actionId: 3,
        actionTitle: "actionTitle",
        actionDescription: "actionDescription",
        actionType: "actionType",
        causeTitle: "causeTitle",
        campaignTitle: "campaignTitle",
        campaignDescription: "campaignDescription",
        organizationContact: "organizationContact",
        organizationTitle: "organizationTitle",
        organizationDescription: "organizationDescription",
        reward: 100},
        {
          actionId: 4,
          actionTitle: "actionTitle",
          actionDescription: "actionDescription",
          actionType: "actionType",
          causeTitle: "causeTitle",
          campaignTitle: "campaignTitle",
          campaignDescription: "campaignDescription",
          organizationContact: "organizationContact",
          organizationTitle: "organizationTitle",
          organizationDescription: "organizationDescription",
          reward: 100},
          {
            actionId: 5,
            actionTitle: "actionTitle",
            actionDescription: "actionDescription",
            actionType: "actionType",
            causeTitle: "causeTitle",
            campaignTitle: "campaignTitle",
            campaignDescription: "campaignDescription",
            organizationContact: "organizationContact",
            organizationTitle: "organizationTitle",
            organizationDescription: "organizationDescription",
            reward: 100},

];
