export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  REGISTERCAUSE: "RegisterCause",
  REGISTERACT: "RegisterAct",
  SETTINGS: "Settings",
  CAMPAIGN: "Campaign",
  RECOVERPASSWORD: "RecoverPassword",
  CONFIRMRECOVERPASSWORD: "ConfirmRecoverPassword",
  UPDATECAUSE: "UpdateCause",
  UPDATEACTION: "UpdateAction",
  CAMPAIGN_DETAILS: "CampaignDetails",
  ORGANIZATION_DETAILS: "OrganizationDetails",
});
