export default Object.freeze({
  DASHBOARD: "Dashboard",
  ACTION_DETAILS: "Action Details",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  REGISTERCAUSE: "RegisterCause",
  REGISTERACT: "RegisterAct",
  SETTINGS: "Settings",
  CAMPAIGN: "Campaign",
  RECOVERPASSWORD: "RecoverPassword",
  CONFIRMRECOVERPASSWORD: "ConfirmRecoverPassword",
  UPDATECAUSE: "Update Cause",
  ORGANIZATION_DETAILS: "Organization Details",
  STATISTICS: "STATISTICS",
  HIDDENACTIONS: "Hidden Actions",
  COMPLETEURL: "Action Complete URL",
  ACTIONLISTING: "Action Listings",
  BADGELISTING: "Badge Listings",
});
