export default Object.freeze({
  ACTION_DETAILS: "ActionDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  REGISTERCAUSE: "RegisterCause",
  REGISTERACT: "RegisterAct",
  SETTINGS: "Settings",
  CAMPAIGN: "Campaign",
  RECOVERPASSWORD: "RecoverPassword",
  CONFIRMRECOVERPASSWORD: "ConfirmRecoverPassword",
  UPDATECAUSE: "UpdateCause",
  UPDATEACTION: "UpdateAction",
  CAMPAIGN_DETAILS: "CampaignDetails",
  ORGANIZATION_DETAILS: "OrganizationDetails",
  MYACTIONS: "MyActions",
  HIDDENACTIONS: "HiddenActions",
  COMPLETEDACTIONS: "CompletedActions"
});
